server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /g58-h2

