spring.application.name=springboot_module
server.port=9090

# Spring Data REST configuration
spring.data.rest.base-path=/api
spring.data.rest.page-param-name=sahifa
spring.data.rest.limit-param-name=limit
spring.data.rest.default-page-size=3

spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true