spring.application.name=springboot_module

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/g58-h2

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

example.string=Salom .properties file
example.languages=Java, Python, Kotlin, Go, C++
example.languages2=Java# Python# Kotlin# Go# C++
example.numbers={'one':'bir', 'two':'ikki', 'three':'uch'}

person.id=1
person.firstName=Ali
person.lastName=Aliyev
person.fullName= ${person.firstName} ${person.lastName}
person.age=29
