spring.application.name=springboot_module
server.port=8080
g58.message=Hello, Spring Boot!

mailing.host=smtp.example.com
mailing.port=587
mailing.username=g58_mailing_user
mailing.password=securepassword
mailing.secret-key=supersecretkey


####################### POSTGRESQL CONFIGURATION ##############################
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.banner.location=classpath:prod-banner.txt
